'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import { VestGPT } from '@/components/home/vestgpt';
// import { Providers } from './providers';
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed bottom-8 right-8 font-bold text-white z-10">
          <VestGPT />
        </div>
        {children}
      </body>
    </html>
  )
}
